{{- if .Values.gateway.enabled }}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ include "midden.fullname" . }}
  labels:
    {{- include "midden.labels" . | nindent 4 }}
spec:
  parentRefs:
    {{- toYaml .Values.gateway.parentRefs | nindent 4 }}
  {{- with .Values.gateway.hostnames }}
  hostnames:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  rules:
    - {{- with .Values.gateway.matches }}
      matches:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      backendRefs:
        - name: {{ include "midden.fullname" . }}
          port: {{ .Values.service.port }}
      {{- with .Values.gateway.filters }}
      filters:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.gateway.requestTimeout }}
      timeouts:
        request: {{ . | quote }}
      {{- end }}
{{- end }}
