{{- if and .Values.secret.create (not .Values.existingSecret) }}
{{- $old := (lookup "v1" "Secret" .Release.Namespace (include "midden.secretName" .)).data | default dict -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "midden.secretName" . }}
  labels:
    {{- include "midden.labels" . | nindent 4 }}
type: Opaque
data:
  {{- $signingKey := .Values.secret.signingKey | default (or (get $old "MIDDEN_SECRET" | b64dec) (randAlphaNum 44)) }}
  {{- with $signingKey }}
  MIDDEN_SECRET: {{ . | b64enc | quote }}
  {{- end }}
  {{- with .Values.secret.adminPassword }}
  MIDDEN_ADMIN_PASSWORD: {{ . | b64enc | quote }}
  {{- end }}
  {{- with .Values.oidc.clientSecret }}
  MIDDEN_OIDC_CLIENT_SECRET: {{ . | b64enc | quote }}
  {{- end }}
{{- end }}
